spring:
    application:
        name: "authentication-service"
    security:
      user:
        name: admin
        password: Msedcl@2026
server:
    port: 8383
eureka:
    instance:
        hostname: localhost
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka/